### ISSUE TITLE
hi, the postprocessing seems have some problem?

### ISSUE THREAD

**Issue by lucasjinreal** [hpc203/yolov7-detect-face-onnxrun-cpp-py#1]
Most of images looks normal, except this image:

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/21303438/201303312-08e4db4a-8dbc-40a9-9a6c-a65c2856ce43.png">

as you can see at first glance, some face are more like horizontal rect rather than normally vertical rect,

what could be the reason?

**Comment by KangChou** [comment]
`Traceback (most recent call last):
  File "D:\CV2022\mymediapipe\yolov7\exe_yolov7\main.py", line 158, in <module>
    dstimg = YOLOv7_face_detector.draw_detections(srcimg, boxes, scores, kpts)
  File "D:\CV2022\mymediapipe\yolov7\exe_yolov7\main.py", line 123, in draw_detections
    x, y, w, h = box.astype(int)
ValueError: not enough values to unpack (expected 4, got 1)`
